mode                = "sequencer"
listen              = "0.0.0.0:8443"
grpc_listen         = "0.0.0.0:50051"
https_cert          = "/etc/eatsimple/origin.crt"
https_key           = "/etc/eatsimple/origin.key"
grpc_cert           = "/etc/eatsimple/seq.crt"
grpc_key            = "/etc/eatsimple/seq.key"
ca_root             = "/etc/eatsimple/ca.pem"
ca_key              = "/etc/eatsimple/ca.key" 
rocksdb_path        = "/var/lib/mychain/blocks"
max_block_entries   = 100        # close the block after 100 entires OR
max_block_age_ms    = 3000       # or close the block after 30 seconds
anchor_interval     = 1000       # blocks
enroll_ttl_days     = 7
witness_threshold   = 2
witness_endpoints   = [
    "https://witness1.local/cosign",
    "https://witness2.local/cosign"
]